### PR TITLE
Allows for use of non-https domains under El Capitan

### LINKED ISSUE #90: App Transport Security failure under OSX 10.11
Sadly, webkit2png now throws App Transport Security errors under El Capitan any time you request a non-https site. Specifically:

```
Fetching http://google.com/ ...
2015-10-02 16:22:21.037 Python[6363:5778368] App Transport Security has blocked a 
cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be 
configured via your app's Info.plist file.
 ... something went wrong: The resource could not be loaded because the App Transport 
Security policy requires the use of a secure connection.
```

Apple's solution (sic.) to this problem -- assuming you can't request an https version of the site -- is to modify your app's .plist to make exceptions for all non-https sites you want to request, or you can turn off ATS altogether in the .plist. (I see, from testing, that Python's urllib2 can request external non-https sites, but webkit2png cannot.)

[Update] Good discussion of some of the underlying Python/NSURL issues here: http://michaellynn.github.io/2015/07/31/customized-python-app-bundles/

### PR DESCRIPTION
**Pull request by bendalton**
... when --ignore-ssl-check is enabled

Fixes #90

### CODE REVIEW

**Comment by banderson623** [comment]
:+1: works great!

**Comment by MarkSHarrison** [comment]
@paulhammond any hint as to when this pull request will be merged?

**Comment by digimix** [comment]
Works when adding the --ignore-ssl-check flag. Thanks @bendalton!

**Comment by ndarville** [comment]
👀

**Comment by raine** [comment]
:+1:

**Comment by zackehh** [comment]
Yeah +1 on getting this merged in.

**Comment by brandonjp** [comment]
Best. Patch. Ever.  
Changed my life.  
Merge it! 
:+1:

**Comment by tonijn** [comment]
+1

**Comment by djui** [comment]
Does not work for me:

```
$ webkit2png --ignore-ssl-check http://localhost:62345/
Fetching http://localhost:62345/pdf-to-excel-api ...
2016-06-01 12:59:58.576 Python[20589:6130909] App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
 ... something went wrong: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

$ head $(which webkit2png)
#!/usr/bin/python

# webkit2png - makes screenshots of web pages
# http://www.paulhammond.org/webkit2png

__version__ = "0.7"

# Copyright (c) 2004-2014 Paul Hammond
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
```

Could it be because the application is running from Docker for Mac (beta)?

**Comment by arturoherrero** [comment]
LGTM :shipit:

**Comment by thisiswangle** [comment]
+1

**Comment by o6uoq** [comment]
+1

**Comment by joeyhoer** [comment]
Will this ever be merged?

**Comment by paulhammond** [comment]
Hi all! Thank you to everyone for reporting this, and to Ben for proposing a fix. I'm sorry it took so long to get this merged; my day job got really really busy and side projects like webkit2png got left behind.

I just pushed a commit containing this fix, and I'm going to get a new version of webkit2png released soon.

**Pull request closed without merging**
